package practicajasperreport;

import java.awt.Color;
import java.awt.Frame;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import practicajasperreport.ListadoEntreCodigos.Tabla;

/**
 *
 * @author yo
 */
public class GestionArticulos extends javax.swing.JDialog {

    Connection con;
    
    enum TiposOperacion {
        BAJA,
        ALTA,
        MODIFICAR,
        CONSULTA,
        NO_SELECCIONADO
    }
    TiposOperacion tipoOperacion = TiposOperacion.NO_SELECCIONADO;
    /**
     * Creates new form GestionClientes
     */
    public GestionArticulos(Frame parent, boolean modal) {
        
        super(parent, modal);
        try {
            con = ConnectionDB.getConnection();
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(this, 
                    "Error de conexión con la BBDD", "Error de conexión", JOptionPane.CLOSED_OPTION);
            this.dispose();
        }
        initComponents();
        setLocationRelativeTo(parent);
        setEnabledFields(getCampos(), null, false);
    }
    
    public GestionArticulos() {}
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    

    
    private void setEnabledFields(JTextField[] campos, JTextField excludedField, boolean state) {
        
        for (JTextField field : campos) {
            
            if (excludedField != null) {
                if (field.getName() != null && field.getName().equalsIgnoreCase(excludedField.getName())) {
                    field.setEnabled(!state);
                } else {
                    field.setEnabled(state);
                }
            } else {
                field.setEnabled(false);
            }
        }
    }
    
    private JTextField[] getCampos() {
    
        JTextField[] campos = {codigo, descripcion, stock, stockMinimo, precioCompra, precioVenta};
        return campos;

    }
    
    private boolean checkArticuloId() {
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT codigo FROM articulos WHERE codigo = " + codigo.getText());

            if (rs.next()) {
                return true;
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(this,
                    "Error de consulta con la BBDD", "Error en la consulta", JOptionPane.CLOSED_OPTION);
        }
        return false;
    }

    private void cargarArticuloPorCodigo() {
        String sql = "SELECT codigo, descripcion, precio_venta, precio_compra, stock, stock_minimo " +
                     "FROM articulos WHERE codigo = " + codigo.getText();

        try (Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql)) {

            if (rs.next()) {
                descripcion.setText(rs.getString("descripcion"));
                stock.setText("" + rs.getFloat("stock"));
                stockMinimo.setText("" + rs.getFloat("stock_minimo"));
                precioCompra.setText("" + rs.getFloat("precio_compra"));
                precioVenta.setText("" + rs.getFloat("precio_venta"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar el artículo",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean validarCamposAlta() {
        if (descripcion.getText().isBlank() ||
            stock.getText().isBlank() ||
            stockMinimo.getText().isBlank() ||
            precioCompra.getText().isBlank() ||
            precioVenta.getText().isBlank()) {

            JOptionPane.showMessageDialog(this,
                    "Rellena todos los campos obligatorios",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void insertarArticulo() {
        String sql = "INSERT INTO articulos " +
                "(codigo, descripcion, stock, stock_minimo, precio_venta, precio_compra) VALUES (" +
                "?, ?, ?, ?, ?, ?)";

        try (PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, Integer.parseInt(codigo.getText()));
            ps.setString(2, descripcion.getText());
            ps.setFloat(3, Float.parseFloat(stock.getText()));
            ps.setFloat(4, Float.parseFloat(stockMinimo.getText()));
            ps.setFloat(5, Float.parseFloat(precioVenta.getText()));
            ps.setFloat(6, Float.parseFloat(precioCompra.getText()));

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Artículo insertado correctamente.");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al insertar el artículo",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
    private void modificarArticulo() {
        String sql = "UPDATE articulos SET " +
                "descripcion = ?, stock = ?, stock_minimo = ?, precio_venta = ?, precio_compra = ? " +
                "WHERE codigo = ?";

        try (var ps = con.prepareStatement(sql)) {

            ps.setString(1, descripcion.getText());
            ps.setFloat(2, Float.parseFloat(stock.getText()));
            ps.setFloat(3, Float.parseFloat(stockMinimo.getText()));
            ps.setFloat(4, Float.parseFloat(precioVenta.getText()));
            ps.setFloat(5, Float.parseFloat(precioCompra.getText()));
            ps.setInt(6, Integer.parseInt(codigo.getText()));

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Artículo modificado correctamente.");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al modificar el artículo",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void borrarArticulo() {
        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Seguro que deseas eliminar el artículo?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION);

        if (opcion != JOptionPane.YES_OPTION) return;

        // Corrección: Tabla articulos
        String sql = "DELETE FROM articulos WHERE codigo = ?";

        try (var ps = con.prepareStatement(sql)) {
            ps.setInt(1, Integer.parseInt(codigo.getText()));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Artículo eliminado correctamente.");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al eliminar el artículo",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    private void cambiarColorCampos(JTextField[] campos, Color color) {
    
        for (JTextField campo: campos) {
            
            campo.setBackground(color);
            
        }
        
    }
    
    private void borrarCampos(JTextField[] campos) {
        
        for (JTextField campo: campos) {
        
            campo.setText("");
            
        }
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        stockMinimo = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        descripcion = new javax.swing.JTextField();
        botonSalir = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        precioCompra = new javax.swing.JTextField();
        precioVenta = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        maintenanceMenu = new javax.swing.JMenu();
        registrationsMaintenanceItem = new javax.swing.JMenuItem();
        cancellationsMaintenanceItem = new javax.swing.JMenuItem();
        modificationsMaintenanceItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        returnMaintenanceItem = new javax.swing.JMenuItem();
        queryMenu = new javax.swing.JMenu();
        listingQueryItem = new javax.swing.JMenu();
        sortByIdItem = new javax.swing.JMenuItem();
        betweenIdsItem = new javax.swing.JMenuItem();
        searchByIdItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Stock mínimo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        stock.setName("stock"); // NOI18N
        stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stockKeyTyped(evt);
            }
        });
        getContentPane().add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 62, -1));

        stockMinimo.setName("stockMinimo"); // NOI18N
        stockMinimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stockMinimoKeyTyped(evt);
            }
        });
        getContentPane().add(stockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 63, -1));

        codigo.setName("codigo"); // NOI18N
        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoKeyTyped(evt);
            }
        });
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 48, -1));

        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jLabel3.setText("Descripción");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));
        getContentPane().add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 168, 118));

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        jLabel13.setText("Stock");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel14.setText("Precio de compra");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel15.setText("Precio de venta");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        precioCompra.setName("movil"); // NOI18N
        precioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioCompraKeyTyped(evt);
            }
        });
        getContentPane().add(precioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 62, -1));

        precioVenta.setName("fax"); // NOI18N
        precioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioVentaKeyTyped(evt);
            }
        });
        getContentPane().add(precioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 63, -1));

        maintenanceMenu.setText("Mantenimiento");

        registrationsMaintenanceItem.setText("Altas");
        registrationsMaintenanceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationsMaintenanceItemActionPerformed(evt);
            }
        });
        maintenanceMenu.add(registrationsMaintenanceItem);

        cancellationsMaintenanceItem.setText("Bajas");
        cancellationsMaintenanceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellationsMaintenanceItemActionPerformed(evt);
            }
        });
        maintenanceMenu.add(cancellationsMaintenanceItem);

        modificationsMaintenanceItem.setText("Modificaciones");
        modificationsMaintenanceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificationsMaintenanceItemActionPerformed(evt);
            }
        });
        maintenanceMenu.add(modificationsMaintenanceItem);
        maintenanceMenu.add(jSeparator2);

        returnMaintenanceItem.setText("Volver");
        returnMaintenanceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMaintenanceItemActionPerformed(evt);
            }
        });
        maintenanceMenu.add(returnMaintenanceItem);

        jMenuBar1.add(maintenanceMenu);

        queryMenu.setText("Consultas");

        listingQueryItem.setText("Listados");

        sortByIdItem.setText("Por Código");
        sortByIdItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByIdItemActionPerformed(evt);
            }
        });
        listingQueryItem.add(sortByIdItem);

        betweenIdsItem.setText("Entre códigos");
        betweenIdsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betweenIdsItemActionPerformed(evt);
            }
        });
        listingQueryItem.add(betweenIdsItem);

        queryMenu.add(listingQueryItem);

        searchByIdItem.setText("Por código");
        searchByIdItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByIdItemActionPerformed(evt);
            }
        });
        queryMenu.add(searchByIdItem);

        jMenuBar1.add(queryMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

        switch (tipoOperacion) {
            case ALTA -> {
                // Eliminadas validaciones de DNI, teléfono, etc.
                if (validarCamposAlta()) {
                    insertarArticulo();
                }
            }
            case BAJA -> borrarArticulo();
            case MODIFICAR -> {
                if (validarCamposAlta()) {
                    modificarArticulo();
                }
            }
            default -> {
                JOptionPane.showMessageDialog(this,
                        "No hay ninguna operación seleccionada",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }

        cambiarColorCampos(getCampos(), Color.WHITE);
        setEnabledFields(getCampos(), null, false);
        codigo.setEnabled(false);
        tipoOperacion = TiposOperacion.NO_SELECCIONADO;
        
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed

        borrarCampos(getCampos());
        cambiarColorCampos(getCampos(), Color.WHITE);
        codigo.grabFocus();
        setEnabledFields(getCampos(), null, true);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        codigo.grabFocus();
        tipoOperacion = TiposOperacion.NO_SELECCIONADO;
        setEnabledFields(getCampos(), null, false);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void registrationsMaintenanceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationsMaintenanceItemActionPerformed
        tipoOperacion = TiposOperacion.ALTA;
        borrarCampos(getCampos());
        cambiarColorCampos(getCampos(), Color.WHITE);
        setEnabledFields(getCampos(), codigo, false);
        codigo.setEnabled(true);
        codigo.grabFocus();
        botonAceptar.setEnabled(true);
    }//GEN-LAST:event_registrationsMaintenanceItemActionPerformed

    private void cancellationsMaintenanceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellationsMaintenanceItemActionPerformed
        tipoOperacion = TiposOperacion.BAJA;
        borrarCampos(getCampos());
        cambiarColorCampos(getCampos(), Color.WHITE);
        setEnabledFields(getCampos(), codigo, false);
        codigo.setEnabled(true);
        codigo.grabFocus();
        botonAceptar.setEnabled(true);
    }//GEN-LAST:event_cancellationsMaintenanceItemActionPerformed

    private void modificationsMaintenanceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificationsMaintenanceItemActionPerformed
        tipoOperacion = TiposOperacion.MODIFICAR;
        borrarCampos(getCampos());
        cambiarColorCampos(getCampos(), Color.WHITE);
        setEnabledFields(getCampos(), codigo, false);
        codigo.setEnabled(true);
        codigo.grabFocus();
        botonAceptar.setEnabled(true);
    }//GEN-LAST:event_modificationsMaintenanceItemActionPerformed

    private void codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyTyped
        
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        
         if (codigo.getText().length() >= 5 ) {
            evt.consume();
        }
    }//GEN-LAST:event_codigoKeyTyped

    private void codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyPressed
       
         if (evt.getKeyCode() == VK_ENTER && codigo.getText().length() == 5) { // Permitimos longitud variable o ajusta a 5 si es estricto

            switch (tipoOperacion) {
                case ALTA -> {
                    if (checkArticuloId()) {
                        JOptionPane.showMessageDialog(this,
                                "El artículo ya existe",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        codigo.setText("");
                    } else {
                        setEnabledFields(getCampos(), codigo, true);
                        codigo.setEnabled(false);
                        // El foco pasa a descripción, ya no hay DNI
                        descripcion.grabFocus();
                    }
                }
                case BAJA, MODIFICAR, CONSULTA -> {
                    if (!checkArticuloId()) {
                        JOptionPane.showMessageDialog(this,
                                "El artículo no existe",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        codigo.setText("");
                    } else {
                        setEnabledFields(getCampos(), codigo, true);
                        codigo.setEnabled(false);
                        
                        cargarArticuloPorCodigo();
                        botonAceptar.setEnabled(true);
                        
                        if (tipoOperacion == TiposOperacion.BAJA || tipoOperacion == TiposOperacion.CONSULTA) {
                            setEnabledFields(getCampos(), null, false);
                            if (tipoOperacion == TiposOperacion.CONSULTA) {
                                botonAceptar.setEnabled(false);
                            }
                        }
                    }
                }
                case NO_SELECCIONADO -> {
                    cargarArticuloPorCodigo();
                    setEnabledFields(getCampos(), null, false);
                }
                default -> System.out.println("No se ha insertado un código correcto.");
            }
        }
    }//GEN-LAST:event_codigoKeyPressed

    private void betweenIdsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betweenIdsItemActionPerformed
        ListadoEntreCodigos dialog =
         new ListadoEntreCodigos((Frame) this.getParent(), true, con, Tabla.ARTICULOS);
        dialog.setVisible(true);
    }//GEN-LAST:event_betweenIdsItemActionPerformed

    private void returnMaintenanceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMaintenanceItemActionPerformed
        this.dispose();
    }//GEN-LAST:event_returnMaintenanceItemActionPerformed

    private void searchByIdItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByIdItemActionPerformed
        tipoOperacion = TiposOperacion.CONSULTA;
        borrarCampos(getCampos());
        cambiarColorCampos(getCampos(), Color.WHITE);
        setEnabledFields(getCampos(), codigo, false);
        codigo.setEnabled(true);
        codigo.grabFocus();
    }//GEN-LAST:event_searchByIdItemActionPerformed

    private void sortByIdItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByIdItemActionPerformed
        mostrarListadoArticulosPorCodigo();
    }//GEN-LAST:event_sortByIdItemActionPerformed

    private void stockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        
    }//GEN-LAST:event_stockKeyTyped

    private void precioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioCompraKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        
    }//GEN-LAST:event_precioCompraKeyTyped

    private void stockMinimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockMinimoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        
    }//GEN-LAST:event_stockMinimoKeyTyped

    private void precioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioVentaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        
    }//GEN-LAST:event_precioVentaKeyTyped

    
    private void mostrarListadoArticulosPorCodigo() {
        try {
           
            JasperReport report = (JasperReport) JRLoader.loadObjectFromFile(
                    "src/main/resources/jasper/ListadoArticulosPorCodigo.jasper");

            JasperPrint print = JasperFillManager.fillReport(report, null, con);

            JasperExportManager.exportReportToPdfFile(print, "src\\main\\resources\\jasper\\ListadoArticulosPorCodigo.pdf");
            setModal(false);
            JasperViewer.viewReport(print, true);
            
        } catch (JRException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error al generar el listado",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionArticulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem betweenIdsItem;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JMenuItem cancellationsMaintenanceItem;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField descripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu listingQueryItem;
    private javax.swing.JMenu maintenanceMenu;
    private javax.swing.JMenuItem modificationsMaintenanceItem;
    private javax.swing.JTextField precioCompra;
    private javax.swing.JTextField precioVenta;
    private javax.swing.JMenu queryMenu;
    private javax.swing.JMenuItem registrationsMaintenanceItem;
    private javax.swing.JMenuItem returnMaintenanceItem;
    private javax.swing.JMenuItem searchByIdItem;
    private javax.swing.JMenuItem sortByIdItem;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField stockMinimo;
    // End of variables declaration//GEN-END:variables
}
