package practicajasperreport;

import java.awt.Color;
import java.awt.Frame;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ChatGPT, Copilot, Gemini, Grok, DeepSeek, Llama, Perplexity
 */
public class GestionClientes extends javax.swing.JDialog {

    Connection con;
    
    enum TiposOperacion {
        BAJA,
        ALTA,
        MODIFICAR,
        NO_SELECCIONADO
    }
    TiposOperacion tipoOperacion = TiposOperacion.NO_SELECCIONADO;
    /**
     * Creates new form GestionClientes
     */
    public GestionClientes(Frame parent, boolean modal) {
        
        super(parent, modal);
        try {
            con = ConnectionDB.getConnection();
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(this, 
                    "Error de conexión con la BBDD", "Error de conexión", JOptionPane.CLOSED_OPTION);
            this.dispose();
        }
        initComponents();
        setLocationRelativeTo(parent);
        setEnabledFields(getCampos(), null, false);
    }
    
    public GestionClientes() {}
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private ResultSet estadisticasPorCodigoPostal() throws SQLException {

        String sql = "SELECT codigo_postal, COUNT(*) total " +
                     "FROM clientes GROUP BY codigo_postal";
        Statement st = con.createStatement();
        return st.executeQuery(sql);
    }
    
    private boolean calcularLetraDni() {

            String textoDni = dni.getText().trim();

            // Validar que no esté vacío y que sean números
            if (textoDni.isEmpty() || !textoDni.matches("\\d+")) {
                JOptionPane.showMessageDialog(this,
                        "Introduce un DNI válido (solo números)",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                letraDni.setText("");
                tipoOperacion = TiposOperacion.NO_SELECCIONADO;
                return false;

            }

            if (textoDni.length() != 8) {
                JOptionPane.showMessageDialog(this,
                    "El DNI debe tener 8 números",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                letraDni.setText("");
                tipoOperacion = TiposOperacion.NO_SELECCIONADO;
                return false;
            }

            int numeroDni;
            try {
                numeroDni = Integer.parseInt(textoDni);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "El DNI es demasiado grande",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                letraDni.setText("");
                tipoOperacion = TiposOperacion.NO_SELECCIONADO;
                return false;
            }

            // Letras del DNI
            String letras = "TRWAGMYFPDXBNJZSQVHLCKE";
            char letra = letras.charAt(numeroDni % 23);

            letraDni.setText(String.valueOf(letra));
            return true;
    }
    
    private boolean validarCodigoPostal() {

        if (!codigoPostal.getText().matches("\\d{5}")) {
            JOptionPane.showMessageDialog(this,
                "El código postal debe tener 5 números",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
    
    private boolean validarTelefono(JTextField campo) {

        if (campo.getText().isBlank()) return true;

        if (!campo.getText().matches("\\d{9}")) {
            JOptionPane.showMessageDialog(this,
                campo.getName() + " debe tener 9 números",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            campo.grabFocus();
            return false;
        }

        return true;
    }
    
    private boolean validarEmail() {

        if (email.getText().isBlank()) return true;

        if (!email.getText().matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
            JOptionPane.showMessageDialog(this,
                "El e-mail no es válido",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
    
    private void setEnabledFields(JTextField[] campos, JTextField excludedField, boolean state) {
        
        for (JTextField field : campos) {
            
            if (excludedField != null) {
                if (field.getName() != null && field.getName().equalsIgnoreCase(excludedField.getName())) {
                    field.setEnabled(!state);
                } else {
                    field.setEnabled(state);
                }
            } else {
                field.setEnabled(false);
            }
        }
    }
    
    private JTextField[] getCampos() {
    
        JTextField[] campos = {codigo, dni, nombre, apellidos, direccion, codigoPostal, localidad, telefono, movil, fax, email, total};
        return campos;

    }
    
    private boolean checkClientId() {
    
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT codigo FROM clientes WHERE codigo = " + codigo.getText());
            
            if (rs.next()) {
                return true;
            } 
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(this, 
                    "Error de consulta con la BBDD", "Error en la consulta", JOptionPane.CLOSED_OPTION);
        }
        
        return false;
    }

    private void cargarClientePorCodigo() {

        String sql = "SELECT codigo, dni, apellidos, nombre, direccion, " +
                     "codigo_postal, localidad, telefono, movil, fax, email, total " +
                     "FROM clientes WHERE codigo = " + codigo.getText();

        try (Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql)) {

            if (rs.next()) {

                dni.setText(rs.getString("dni").substring(0, 8));
                letraDni.setText(rs.getString("dni").substring(8));

                apellidos.setText(rs.getString("apellidos"));
                nombre.setText(rs.getString("nombre"));
                direccion.setText(rs.getString("direccion"));
                codigoPostal.setText(rs.getString("codigo_postal"));
                localidad.setText(rs.getString("localidad"));
                telefono.setText(rs.getString("telefono"));
                movil.setText(rs.getString("movil"));
                fax.setText(rs.getString("fax"));
                email.setText(rs.getString("email"));
                total.setText(String.valueOf(rs.getFloat("total")));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar el cliente",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean validarCamposAlta() {

        if (dni.getText().isBlank() ||
            nombre.getText().isBlank() ||
            apellidos.getText().isBlank() ||
            direccion.getText().isBlank() ||
            codigoPostal.getText().isBlank() ||
            localidad.getText().isBlank()) {

            JOptionPane.showMessageDialog(this,
                "Rellena todos los campos obligatorios",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
    
    private void insertarCliente() {

        String sql = "INSERT INTO clientes " +
            "(codigo, dni, apellidos, nombre, direccion, codigo_postal, localidad, " +
            "telefono, movil, fax, email, total) VALUES (" +
            "?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try (PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, Integer.parseInt(codigo.getText()));
            ps.setString(2, dni.getText() + letraDni.getText());
            ps.setString(3, apellidos.getText());
            ps.setString(4, nombre.getText());
            ps.setString(5, direccion.getText());
            ps.setString(6, codigoPostal.getText());
            ps.setString(7, localidad.getText());
            ps.setString(8, telefono.getText());
            ps.setString(9, movil.getText());
            ps.setString(10, fax.getText());
            ps.setString(11, email.getText());
            ps.setFloat(12, 0);

            ps.executeUpdate();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                "Error al insertar el cliente",
                "Error",
                JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
        }
    }
    
    private void modificarCliente() {

        String sql = "UPDATE clientes SET " +
            "dni = ?, apellidos = ?, nombre = ?, direccion = ?, codigo_postal = ?, " +
            "localidad = ?, telefono = ?, movil = ?, fax = ?, email = ? " +
            "WHERE codigo = ?";

        try (var ps = con.prepareStatement(sql)) {

            ps.setString(1, dni.getText() + letraDni.getText());
            ps.setString(2, apellidos.getText());
            ps.setString(3, nombre.getText());
            ps.setString(4, direccion.getText());
            ps.setString(5, codigoPostal.getText());
            ps.setString(6, localidad.getText());
            ps.setString(7, telefono.getText());
            ps.setString(8, movil.getText());
            ps.setString(9, fax.getText());
            ps.setString(10, email.getText());
            ps.setInt(11, Integer.parseInt(codigo.getText()));

            ps.executeUpdate();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                "Error al modificar el cliente",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void borrarCliente() {

        int opcion = JOptionPane.showConfirmDialog(this,
            "¿Seguro que deseas eliminar el cliente?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION);

        if (opcion != JOptionPane.YES_OPTION) return;

        String sql = "DELETE FROM clientes WHERE codigo = ?";

        try (var ps = con.prepareStatement(sql)) {

            ps.setString(1, codigo.getText());
            ps.executeUpdate();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                "Error al eliminar el cliente",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean compruebaCampoSinNum(JTextField campo) {
    
        if (campo.getText().contains("0123456789") || campo.getText().isBlank()) {
        
            campo.grabFocus();
            campo.setBackground(new Color(0xFF6666));
            return false;
        } else {
        
            return true;
        }
        
    }
    
    private boolean compruebaCampoNum(JTextField campo, int lengthCampo) {
    
        if (campo.getText().length() != lengthCampo) {
        
            return false;
            
        } 
        else {
            
            try {
            
                Integer.parseInt(campo.getText());
                return true;
            } catch (NumberFormatException nfe) {

               return false;
            }
            
        }
        
    }
    private void cambiarColorCampos(JTextField[] campos, Color color) {
    
        for (JTextField campo: campos) {
            
            campo.setBackground(color);
            
        }
        
    }
    
    private void borrarCampos(JTextField[] campos) {
        
        for (JTextField campo: campos) {
        
            campo.setText("");
            
        }
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        codigoPostal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        localidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        movil = new javax.swing.JTextField();
        fax = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        dni = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        letraDni = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        maintenanceMenu = new javax.swing.JMenu();
        registrationsMaintenanceItem = new javax.swing.JMenuItem();
        cancellationsMaintenanceItem = new javax.swing.JMenuItem();
        modificationsMaintenanceItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        returnMaintenanceItem = new javax.swing.JMenuItem();
        queryMenu = new javax.swing.JMenu();
        sortByIdQueryItem = new javax.swing.JMenu();
        searchByIdItem = new javax.swing.JMenuItem();
        betweenIdsItem = new javax.swing.JMenuItem();
        chartItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setText("C.P.");

        jLabel7.setText("Localidad");

        jLabel8.setText("Teléfono");

        jLabel9.setText("Móvil");

        jLabel10.setText("Fax");

        telefono.setName("telefono"); // NOI18N

        movil.setName("movil"); // NOI18N

        fax.setName("fax"); // NOI18N

        jLabel11.setText("E-mail");

        codigo.setName("codigo"); // NOI18N
        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoKeyTyped(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel12.setText("Total");

        jLabel2.setText("N.I.F");

        dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        letraDni.setEnabled(false);

        jLabel4.setText("Apellidos");

        jLabel5.setText("Domicilio");

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        maintenanceMenu.setText("Mantenimiento");

        registrationsMaintenanceItem.setText("Altas");
        registrationsMaintenanceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationsMaintenanceItemActionPerformed(evt);
            }
        });
        maintenanceMenu.add(registrationsMaintenanceItem);

        cancellationsMaintenanceItem.setText("Bajas");
        cancellationsMaintenanceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellationsMaintenanceItemActionPerformed(evt);
            }
        });
        maintenanceMenu.add(cancellationsMaintenanceItem);

        modificationsMaintenanceItem.setText("Modificaciones");
        modificationsMaintenanceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificationsMaintenanceItemActionPerformed(evt);
            }
        });
        maintenanceMenu.add(modificationsMaintenanceItem);
        maintenanceMenu.add(jSeparator2);

        returnMaintenanceItem.setText("Volver");
        returnMaintenanceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMaintenanceItemActionPerformed(evt);
            }
        });
        maintenanceMenu.add(returnMaintenanceItem);

        jMenuBar1.add(maintenanceMenu);

        queryMenu.setText("Consultas");

        sortByIdQueryItem.setText("Por Código");
        sortByIdQueryItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByIdQueryItemActionPerformed(evt);
            }
        });

        searchByIdItem.setText("Por Código");
        sortByIdQueryItem.add(searchByIdItem);

        betweenIdsItem.setText("Entre códigos");
        betweenIdsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betweenIdsItemActionPerformed(evt);
            }
        });
        sortByIdQueryItem.add(betweenIdsItem);

        chartItem.setText("Gráficos");
        chartItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartItemActionPerformed(evt);
            }
        });
        sortByIdQueryItem.add(chartItem);

        queryMenu.add(sortByIdQueryItem);

        jMenuBar1.add(queryMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(codigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(localidad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(movil, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fax, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel11)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCancelar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(total))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel9)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel10))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccion)
                            .addComponent(apellidos)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(letraDni, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 106, Short.MAX_VALUE))
                                    .addComponent(nombre))))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letraDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar)
                    .addComponent(botonSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

         switch (tipoOperacion) {
            case ALTA -> {
                if (validarCamposAlta() &&
                    calcularLetraDni() &&
                    validarCodigoPostal() &&
                    validarTelefono(telefono) &&
                    validarTelefono(movil) &&
                    validarTelefono(fax) &&
                    validarEmail()) {

                    insertarCliente();
                }
            }
            case BAJA -> borrarCliente();
            case MODIFICAR -> {
                if (calcularLetraDni() &&
                    validarCodigoPostal() &&
                    validarTelefono(telefono) &&
                    validarTelefono(movil) &&
                    validarTelefono(fax) &&
                    validarEmail()) {

                    modificarCliente();
                }
            }
            default -> {
                JOptionPane.showMessageDialog(this,
                    "No hay ninguna operación seleccionada",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
        
         borrarCampos(getCampos());
        cambiarColorCampos(getCampos(), Color.WHITE);
        setEnabledFields(getCampos(), null, false);
        codigo.setEnabled(false);
        tipoOperacion = TiposOperacion.NO_SELECCIONADO;
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed

        borrarCampos(getCampos());
        cambiarColorCampos(getCampos(), Color.WHITE);
        codigo.grabFocus();
        tipoOperacion = TiposOperacion.NO_SELECCIONADO;
        setEnabledFields(getCampos(), null, false);
        codigo.setEnabled(false);

    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void chartItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartItemActionPerformed
        mostrarGraficoClientes();
    }//GEN-LAST:event_chartItemActionPerformed

    private void registrationsMaintenanceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationsMaintenanceItemActionPerformed
        tipoOperacion = TiposOperacion.ALTA;
        borrarCampos(getCampos());
        cambiarColorCampos(getCampos(), Color.WHITE);
        setEnabledFields(getCampos(), codigo, false);
        codigo.setEnabled(true);
        codigo.grabFocus();
    }//GEN-LAST:event_registrationsMaintenanceItemActionPerformed

    private void cancellationsMaintenanceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellationsMaintenanceItemActionPerformed
        tipoOperacion = TiposOperacion.BAJA;
        borrarCampos(getCampos());
        cambiarColorCampos(getCampos(), Color.WHITE);
        setEnabledFields(getCampos(), codigo, false);
        codigo.setEnabled(true);
        codigo.grabFocus();
    }//GEN-LAST:event_cancellationsMaintenanceItemActionPerformed

    private void modificationsMaintenanceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificationsMaintenanceItemActionPerformed
        tipoOperacion = TiposOperacion.MODIFICAR;
        borrarCampos(getCampos());
        cambiarColorCampos(getCampos(), Color.WHITE);
        setEnabledFields(getCampos(), codigo, false);
        codigo.setEnabled(true);
        codigo.grabFocus();
    }//GEN-LAST:event_modificationsMaintenanceItemActionPerformed

    private void codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyTyped
        
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        
         if (codigo.getText().length() >= 5 ) {
            evt.consume();
        }
    }//GEN-LAST:event_codigoKeyTyped

    private void codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyPressed
       
        if (evt.getKeyCode() == VK_ENTER && codigo.getText().length() == 5) {
            
            switch (tipoOperacion) {
                case ALTA -> {
                    
                    if (checkClientId()) {
                        JOptionPane.showMessageDialog(this,
                            "El cliente ya existe",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                        codigo.setText("");
                    } else {
                        setEnabledFields(getCampos(), codigo, true);
                        codigo.setEnabled(false);
                        total.setText("0");
                        total.setEnabled(false);
                        dni.grabFocus();
    }
                }
                case BAJA, MODIFICAR -> {
                    
                    if (!checkClientId()) {
                        JOptionPane.showMessageDialog(this,
                            "El cliente no existe",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                        codigo.setText("");
                    } else {
                        setEnabledFields(getCampos(), codigo, true);
                        codigo.setEnabled(false);
                        total.setEnabled(false);
                        cargarClientePorCodigo();
                        if (tipoOperacion == TiposOperacion.BAJA) {
                            setEnabledFields(getCampos(), null, false);
                        }

                    }
                }
                case NO_SELECCIONADO->{
                
                    cargarClientePorCodigo();
                    setEnabledFields(getCampos(), null, false);
                }
                default -> System.out.println("No se ha insertado un código correcto.");
            }
        } 
    }//GEN-LAST:event_codigoKeyPressed

    private void dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniActionPerformed
        calcularLetraDni();
    }//GEN-LAST:event_dniActionPerformed

    private void sortByIdQueryItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByIdQueryItemActionPerformed
        tipoOperacion = TiposOperacion.NO_SELECCIONADO;

        borrarCampos(getCampos());
        cambiarColorCampos(getCampos(), Color.WHITE);

        setEnabledFields(getCampos(), codigo, false);
        codigo.setEnabled(true);
        codigo.grabFocus();
    }//GEN-LAST:event_sortByIdQueryItemActionPerformed

    private void betweenIdsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betweenIdsItemActionPerformed
        ListadoEntreCodigos dialog =
         new ListadoEntreCodigos((Frame) this.getParent(), true, con);
        dialog.setVisible(true);
    }//GEN-LAST:event_betweenIdsItemActionPerformed

    private void returnMaintenanceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMaintenanceItemActionPerformed
        this.dispose();
    }//GEN-LAST:event_returnMaintenanceItemActionPerformed

    private ResultSet listadoClientesPorCodigo() throws SQLException {

        String sql = "SELECT * FROM clientes ORDER BY codigo";
        Statement st = con.createStatement();
        return st.executeQuery(sql);
    }
    
    private void mostrarGraficoClientes() {

        try {
            JasperReport report = JasperCompileManager.compileReport(
                getClass().getResourceAsStream("src/main/resources/jasper/GraficoClientesPorCP.jrxml")
            );

            JasperPrint print = JasperFillManager.fillReport(
                report,
                null,   // sin parámetros
                con     // tu conexión JDBC
            );

            JasperViewer.viewReport(print, false);

        } catch (JRException ex) {
            JOptionPane.showMessageDialog(this,
                "Error al generar el gráfico",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidos;
    private javax.swing.JMenuItem betweenIdsItem;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JMenuItem cancellationsMaintenanceItem;
    private javax.swing.JMenuItem chartItem;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField codigoPostal;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextField letraDni;
    private javax.swing.JTextField localidad;
    private javax.swing.JMenu maintenanceMenu;
    private javax.swing.JMenuItem modificationsMaintenanceItem;
    private javax.swing.JTextField movil;
    private javax.swing.JTextField nombre;
    private javax.swing.JMenu queryMenu;
    private javax.swing.JMenuItem registrationsMaintenanceItem;
    private javax.swing.JMenuItem returnMaintenanceItem;
    private javax.swing.JMenuItem searchByIdItem;
    private javax.swing.JMenu sortByIdQueryItem;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
